const Map<String, String> ar = {
  "Search": "البحث",
  "Sign In": "تسجيل دخول",
  "Contact us": "تواصل معنا",
  "Rate Us": "قيمنا",
  "Privacy policy": "سياسة الخصوصية",
  "Terms & Conditions": "شروط وأحكام",
  "Common questions": "الأسئلة الشائعة",
  "Favorite": "المفضلة",
  "Add a discount code": "إضافة كود خصم",
  "Store details": "تفاصيل المتجر",
  "Store name": "اسم المتجر",
  " Store Link": "رابط المتجر",
  "Upload Logo": "تحميل الشعار",
  "Jpg": "(SVG او PNG , JPEG )حاول تحميل شعار أبعاد مربعة* ",
  "Discount Details": "تفاصيل الخصم",
  "Type:": ":النوع",
  "offer": "عرض",
  "Countries": "الدول",
  "copuon": "قسيمة",
  "Link offer": "رابط العرض",
  "Copun code": "كود الخصم",
  "Start Date": "تاريح البداية",
  "End Date": "تاريخ الانتهاء",
  "Date is not selected": "لم يتم تحديد التاريخ",
  " Descreotion(optional)": "التفاصيل (اختياري)",
  "Addition Terms": "شروط الإضافة",
  "e-shop": "يجب ان يكون متجرا الإلكتروني",
  "Valid": "فعال",
  "frequent":
      "- إذا كان المتجر الإلكتروني متكررًا ، فيجب أن يكون العرض مختلفًا",
  "Add": "إضافة",
  "Required": "مطلوب",
  "CANCEL": "إلغاء",
  "Ok": "تم",
  "Stores": "متاجر",
  "Home": "الرئيسية",
  "Menu": "قائمة",
  "Last Valid use:": "آخر استخدام صالح:",
  'vaild': "فعال",
  "invalid": "غير فعال",
  "Details": "التفاصيل",
  "offers": "الخصم",
  "show now": "اعرض الان",
  "Login": "تسجيل الدخول",
  "Email": "البريد الإلكتروني",
  "password": "كلمة السر",
  "Forget Your passwor?": "نسيت كلمة السر",
  "New User ? ": "مستخدم جديد ؟",
  "Sign Up": "إنشاء حساب",
  "UserName": "الإسم",
  "Sign": "تسجيل جديد",
  "Done": "تم",
  "Add Copoun": "إضافة قسيمية",
  "Log Out": "تسجيل خروح",
  "Copy": "نسخ",
  "Sorry": "آسف",
  "Content": "لا يمكنك إضافة قسيمتك  الا عند  تسجيل الدخول",
  "My Account": "ملفي الشخصي",
  "Edit Account": "تفاصيل الحساب",
  "verifiy": "الرجاء تفعيل حسابك من خلال الرابط في بريدك الاكتروني",
  "Error": "خطأ",
  "No internet connection": "لايوجد اتصال بالانترنت",
  "Username is not Empty": " اسم المستحدم لا يجب ان يكون فارغ ",
  "Eamil is not vaild": "البريد الإلكتروني غير صالح",
  "favourites": "لا توجد قسائم للمفضلة",
  "About us": "من نحن؟"
};
